tinystories_default_config = {
    "name": "tinystories_default",
    "training_file": "/Users/luyaoli/code/cs336/assignment1-basics/tests/fixtures/tinystories_sample.txt",
    "vocab_size": 10000,
    "special_tokens": ["<|endoftext|>"],
    "context_length": 256,
    "batch_size": 32,
    "num_layers": 4,
    "num_heads": 16,
    "d_model": 512,
    "d_ff": 1344,
    "theta": 10000,
    "iterations": 1000,
    "model_output": f"/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/output/model_tinystories_default",
    "memmap_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/model_tinystories_default_memmap_output",
    "checkpoint_path": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/checkpoint_tinystories_default",
    "checkpoint_freq": 10,
}

tinystories_silu_config = {
    "name": "tinystories_silu",
    "training_file": "/Users/luyaoli/code/cs336/assignment1-basics/tests/fixtures/tinystories_sample.txt",
    "vocab_size": 10000,
    "special_tokens": ["<|endoftext|>"],
    "context_length": 256,
    "batch_size": 32,
    "num_layers": 4,
    "num_heads": 16,
    "d_model": 512,
    "d_ff": 2048,
    "theta": 10000,
    "iterations": 5000,
    "model_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/output/model_tinystories_silu",
    "memmap_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/model_tinystories_silu_memmap_output",
    "checkpoint_path": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/checkpoint_tinystories_silu",
    "checkpoint_freq": 10,
}


tinystories_post_norm_config = {
    "name": "tinystories_post_norm",
    "training_file": "/Users/luyaoli/code/cs336/assignment1-basics/tests/fixtures/tinystories_sample.txt",
    "vocab_size": 10000,
    "special_tokens": ["<|endoftext|>"],
    "context_length": 256,
    "batch_size": 32,
    "num_layers": 4,
    "num_heads": 16,
    "d_model": 512,
    "d_ff": 1344,
    "theta": 10000,
    "iterations": 3000,
    "model_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/output/model_tinystories_post_norm",
    "memmap_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/model_tinystories_post_norm_memmap_output",
    "checkpoint_path": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/checkpoint_tinystories_post_norm",
    "checkpoint_freq": 10,
}

tinystories_no_rope_config = {
    "name": "tinystories_no_rope",
    "training_file": "/Users/luyaoli/code/cs336/assignment1-basics/tests/fixtures/tinystories_sample.txt",
    "vocab_size": 10000,
    "special_tokens": ["<|endoftext|>"],
    "context_length": 256,
    "batch_size": 32,
    "num_layers": 4,
    "num_heads": 16,
    "d_model": 512,
    "d_ff": 1344,
    "theta": None,
    "iterations": 3000,
    "model_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/output/model_tinystories_no_rope",
    "memmap_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/model_tinystories_no_rope_memmap_output",
    "checkpoint_path": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/checkpoint_tinystories_no_rope",
    "checkpoint_freq": 10,
}

tinystories_layer_ablation_config = {
    "name": "tinystories_layer_ablation",
    "training_file": "/Users/luyaoli/code/cs336/assignment1-basics/tests/fixtures/tinystories_sample.txt",
    "vocab_size": 10000,
    "special_tokens": ["<|endoftext|>"],
    "context_length": 256,
    "batch_size": 32,
    "num_layers": 4,
    "num_heads": 16,
    "d_model": 512,
    "d_ff": 1344,
    "theta": 10000,
    "iterations": 1000,
    "model_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/output/model_tinystories_layer_ablation_with_lr_schedule_g_clipping",
    "memmap_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/model_tinystories_layer_ablation_memmap_output",
    "checkpoint_path": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/checkpoint_tinystories_layer_ablation_with_lr_schedule_g_clipping",
    "checkpoint_freq": 10,
}

# openwebtext_config = {
#     "name": "owt_sample",
#     "is_input_dir": True,
#     "training_file": "/Users/luyaoli/code/cs336/assignment1-basics/owt_sample",
#     "context_length": 512,
#     "batch_size": 32,
#     "num_layers": 8,
#     "num_heads": 16,
#     "d_model": 1024,
#     "d_ff": 2688,
#     "theta": 10000,
#     "iterations": 10000,
#     "vocab_size": 10000,
#     "tmp_output_dir": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/",
#     "output_dir": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/output/",
#     "model_output": "owt_sample_model",
#     "memmap_output": "owt_sample_memmap.bin",
#     "checkpoint_output": "owt_sample_checkpoint",
#     "checkpoint_freq": 10,
# }

openwebtext_config = {
    "name": "owt",
    "is_input_dir": False,
    "training_file": "/workspace/data/owt_train.txt",
    "context_length": 512,
    "batch_size": 32,
    "num_layers": 8,
    "num_heads": 16,
    "d_model": 1024,
    "d_ff": 2688,
    "theta": 10000,
    "iterations": 10000,
    "vocab_size": 10000,
    "tmp_output_dir": "/workspace/code/assignment1-basics/cs336_basics/tmp/",
    "bin_output_dir": "/workspace/code/assignment1-basics/cs336_basics/bin/",
    "output_dir": "/workspace/code/assignment1-basics/cs336_basics/output/",
    "model_output": "owt_model",
    "memmap_output": "owt_memmap.bin",
    "checkpoint_output": "owt_checkpoint",
    "checkpoint_freq": 10,
}

openwebtext_tiktoken_config_orig = {
    "name": "openwebtext_10pct_tiktoken",
    "is_input_dir": True,
    "training_file": "/Users/luyaoli/code/cs336/assignment1-basics/owt_sample",
    "context_length": 512,
    "batch_size": 32,
    "num_layers": 8,
    "num_heads": 16,
    "d_model": 1024,
    "d_ff": 2688,
    "theta": 10000,
    "vocab_size": 10000,
    "iterations": 10000,
    "model_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/output/model_openwebtext_full_tiktoken",
    "memmap_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/model_openwebtext_memmap_output_full_tiktoken",
    "checkpoint_path": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/checkpoint_openwebtext_full_tiktoken",
    "checkpoint_freq": 10,
}

openwebtext_tiktoken_config_1024 = {
    "name": "openwebtext_10pct_tiktoken",
    "is_input_dir": True,
    "training_file": "/Users/luyaoli/code/cs336/assignment1-basics/owt_text_10pct",
    "context_length": 256,
    "batch_size": 32,
    "num_layers": 10,
    "num_heads": 16,
    "d_model": 1024,
    "d_ff": 2688,
    "theta": 32000,
    "iterations": 3291,
    "model_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/output/model_openwebtext_full_tiktoken",
    "memmap_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/model_openwebtext_memmap_output_full_tiktoken",
    "checkpoint_path": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/checkpoint_openwebtext_full_tiktoken",
    "checkpoint_freq": 10,
}

openwebtext_tiktoken_config = {
    "name": "openwebtext_10pct_tiktoken",
    "is_input_dir": True,
    "training_file": "/Users/luyaoli/code/cs336/assignment1-basics/owt_text_1pct",
    "context_length": 256,
    "batch_size": 32,
    "num_layers": 8,
    "num_heads": 16,
    "d_model": 512,
    "d_ff": 1344,
    "theta": 32000,
    "iterations": 37000,
    "model_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/output/model_openwebtext_full_tiktoken",
    "memmap_output": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/model_openwebtext_memmap_output_full_tiktoken",
    "checkpoint_path": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/checkpoint_openwebtext_full_tiktoken",
    "checkpoint_freq": 10,
}

tinystories_5M_config_v3 = {
    "name": "tinystories_5M",
    "is_input_dir": False,
    "training_file": "/Users/luyaoli/code/cs336/assignment1-basics/tests/fixtures/tinystories_sample_5M.txt",
    "vocab_size": 10000,
    "context_length": 256,
    "batch_size": 32,
    "num_layers": 8,
    "num_heads": 16,
    "d_model": 1024,
    "d_ff": 2688,
    "theta": 32000,
    "iterations": 3000,
    "tmp_output_dir": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/tmp/",
    "output_dir": "/Users/luyaoli/code/cs336/assignment1-basics/cs336_basics/output/",
    "model_output": "tinystories_5M_model",
    "memmap_output": "tinystories_5M_memmap.bin",
    "checkpoint_output": "tinystories_5M_checkpoint",
    "checkpoint_freq": 10,
}
